// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: seq2seq_service.proto

#include "seq2seq_service.pb.h"
#include "seq2seq_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Seq2SeqGRPC {

static const char* Seq2SeqService_method_names[] = {
  "/Seq2SeqGRPC.Seq2SeqService/RespondToText",
};

std::unique_ptr< Seq2SeqService::Stub> Seq2SeqService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Seq2SeqService::Stub> stub(new Seq2SeqService::Stub(channel));
  return stub;
}

Seq2SeqService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_RespondToText_(Seq2SeqService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Seq2SeqService::Stub::RespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::Seq2SeqGRPC::ConversationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RespondToText_, context, request, response);
}

void Seq2SeqService::Stub::experimental_async::RespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput* request, ::Seq2SeqGRPC::ConversationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RespondToText_, context, request, response, std::move(f));
}

void Seq2SeqService::Stub::experimental_async::RespondToText(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Seq2SeqGRPC::ConversationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RespondToText_, context, request, response, std::move(f));
}

void Seq2SeqService::Stub::experimental_async::RespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput* request, ::Seq2SeqGRPC::ConversationResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RespondToText_, context, request, response, reactor);
}

void Seq2SeqService::Stub::experimental_async::RespondToText(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Seq2SeqGRPC::ConversationResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RespondToText_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Seq2SeqGRPC::ConversationResponse>* Seq2SeqService::Stub::AsyncRespondToTextRaw(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Seq2SeqGRPC::ConversationResponse>::Create(channel_.get(), cq, rpcmethod_RespondToText_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Seq2SeqGRPC::ConversationResponse>* Seq2SeqService::Stub::PrepareAsyncRespondToTextRaw(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Seq2SeqGRPC::ConversationResponse>::Create(channel_.get(), cq, rpcmethod_RespondToText_, context, request, false);
}

Seq2SeqService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Seq2SeqService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Seq2SeqService::Service, ::Seq2SeqGRPC::ConversationInput, ::Seq2SeqGRPC::ConversationResponse>(
          [](Seq2SeqService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::Seq2SeqGRPC::ConversationInput* req,
             ::Seq2SeqGRPC::ConversationResponse* resp) {
               return service->RespondToText(ctx, req, resp);
             }, this)));
}

Seq2SeqService::Service::~Service() {
}

::grpc::Status Seq2SeqService::Service::RespondToText(::grpc::ServerContext* context, const ::Seq2SeqGRPC::ConversationInput* request, ::Seq2SeqGRPC::ConversationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Seq2SeqGRPC

