// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seq2seq_service.proto

#include "seq2seq_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace Seq2SeqGRPC {
class ConversationInputDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ConversationInput> _instance;
} _ConversationInput_default_instance_;
class ConversationResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ConversationResponse> _instance;
} _ConversationResponse_default_instance_;
}  // namespace Seq2SeqGRPC
static void InitDefaultsscc_info_ConversationInput_seq2seq_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Seq2SeqGRPC::_ConversationInput_default_instance_;
    new (ptr) ::Seq2SeqGRPC::ConversationInput();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Seq2SeqGRPC::ConversationInput::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ConversationInput_seq2seq_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ConversationInput_seq2seq_5fservice_2eproto}, {}};

static void InitDefaultsscc_info_ConversationResponse_seq2seq_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Seq2SeqGRPC::_ConversationResponse_default_instance_;
    new (ptr) ::Seq2SeqGRPC::ConversationResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Seq2SeqGRPC::ConversationResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ConversationResponse_seq2seq_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ConversationResponse_seq2seq_5fservice_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_seq2seq_5fservice_2eproto[2];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_seq2seq_5fservice_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_seq2seq_5fservice_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_seq2seq_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationInput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationInput, trans_id_),
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationInput, text_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationResponse, trans_id_),
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationResponse, state_),
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationResponse, text_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Seq2SeqGRPC::ConversationInput)},
  { 7, -1, sizeof(::Seq2SeqGRPC::ConversationResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Seq2SeqGRPC::_ConversationInput_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Seq2SeqGRPC::_ConversationResponse_default_instance_),
};

const char descriptor_table_protodef_seq2seq_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025seq2seq_service.proto\022\013Seq2SeqGRPC\"3\n\021"
  "ConversationInput\022\020\n\010trans_id\030\001 \001(\t\022\014\n\004t"
  "ext\030\002 \001(\t\"\240\001\n\024ConversationResponse\022\020\n\010tr"
  "ans_id\030\001 \001(\t\0226\n\005state\030\002 \001(\0162\'.Seq2SeqGRP"
  "C.ConversationResponse.State\022\014\n\004text\030\003 \001"
  "(\t\"0\n\005State\022\013\n\007SUCCESS\020\000\022\r\n\tMODEL_ERR\020\001\022"
  "\013\n\007UNKNOWN\020\0022d\n\016Seq2SeqService\022R\n\rRespon"
  "dToText\022\036.Seq2SeqGRPC.ConversationInput\032"
  "!.Seq2SeqGRPC.ConversationResponseB\006\242\002\003R"
  "TGb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_seq2seq_5fservice_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_seq2seq_5fservice_2eproto_sccs[2] = {
  &scc_info_ConversationInput_seq2seq_5fservice_2eproto.base,
  &scc_info_ConversationResponse_seq2seq_5fservice_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_seq2seq_5fservice_2eproto_once;
static bool descriptor_table_seq2seq_5fservice_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_seq2seq_5fservice_2eproto = {
  &descriptor_table_seq2seq_5fservice_2eproto_initialized, descriptor_table_protodef_seq2seq_5fservice_2eproto, "seq2seq_service.proto", 370,
  &descriptor_table_seq2seq_5fservice_2eproto_once, descriptor_table_seq2seq_5fservice_2eproto_sccs, descriptor_table_seq2seq_5fservice_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_seq2seq_5fservice_2eproto::offsets,
  file_level_metadata_seq2seq_5fservice_2eproto, 2, file_level_enum_descriptors_seq2seq_5fservice_2eproto, file_level_service_descriptors_seq2seq_5fservice_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_seq2seq_5fservice_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_seq2seq_5fservice_2eproto), true);
namespace Seq2SeqGRPC {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ConversationResponse_State_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_seq2seq_5fservice_2eproto);
  return file_level_enum_descriptors_seq2seq_5fservice_2eproto[0];
}
bool ConversationResponse_State_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ConversationResponse_State ConversationResponse::SUCCESS;
constexpr ConversationResponse_State ConversationResponse::MODEL_ERR;
constexpr ConversationResponse_State ConversationResponse::UNKNOWN;
constexpr ConversationResponse_State ConversationResponse::State_MIN;
constexpr ConversationResponse_State ConversationResponse::State_MAX;
constexpr int ConversationResponse::State_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void ConversationInput::InitAsDefaultInstance() {
}
class ConversationInput::_Internal {
 public:
};

ConversationInput::ConversationInput()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Seq2SeqGRPC.ConversationInput)
}
ConversationInput::ConversationInput(const ConversationInput& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  trans_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_trans_id().empty()) {
    trans_id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.trans_id_);
  }
  text_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_text().empty()) {
    text_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
  // @@protoc_insertion_point(copy_constructor:Seq2SeqGRPC.ConversationInput)
}

void ConversationInput::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ConversationInput_seq2seq_5fservice_2eproto.base);
  trans_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  text_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

ConversationInput::~ConversationInput() {
  // @@protoc_insertion_point(destructor:Seq2SeqGRPC.ConversationInput)
  SharedDtor();
}

void ConversationInput::SharedDtor() {
  trans_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  text_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ConversationInput::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ConversationInput& ConversationInput::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ConversationInput_seq2seq_5fservice_2eproto.base);
  return *internal_default_instance();
}


void ConversationInput::Clear() {
// @@protoc_insertion_point(message_clear_start:Seq2SeqGRPC.ConversationInput)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  trans_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  text_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* ConversationInput::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string trans_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_trans_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Seq2SeqGRPC.ConversationInput.trans_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string text = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_text();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Seq2SeqGRPC.ConversationInput.text"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ConversationInput::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Seq2SeqGRPC.ConversationInput)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string trans_id = 1;
  if (this->trans_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_trans_id().data(), static_cast<int>(this->_internal_trans_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Seq2SeqGRPC.ConversationInput.trans_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_trans_id(), target);
  }

  // string text = 2;
  if (this->text().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_text().data(), static_cast<int>(this->_internal_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Seq2SeqGRPC.ConversationInput.text");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_text(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Seq2SeqGRPC.ConversationInput)
  return target;
}

size_t ConversationInput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Seq2SeqGRPC.ConversationInput)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string trans_id = 1;
  if (this->trans_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_trans_id());
  }

  // string text = 2;
  if (this->text().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_text());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConversationInput::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Seq2SeqGRPC.ConversationInput)
  GOOGLE_DCHECK_NE(&from, this);
  const ConversationInput* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ConversationInput>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Seq2SeqGRPC.ConversationInput)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Seq2SeqGRPC.ConversationInput)
    MergeFrom(*source);
  }
}

void ConversationInput::MergeFrom(const ConversationInput& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Seq2SeqGRPC.ConversationInput)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.trans_id().size() > 0) {

    trans_id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.trans_id_);
  }
  if (from.text().size() > 0) {

    text_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
}

void ConversationInput::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Seq2SeqGRPC.ConversationInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConversationInput::CopyFrom(const ConversationInput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Seq2SeqGRPC.ConversationInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConversationInput::IsInitialized() const {
  return true;
}

void ConversationInput::InternalSwap(ConversationInput* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  trans_id_.Swap(&other->trans_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  text_.Swap(&other->text_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata ConversationInput::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ConversationResponse::InitAsDefaultInstance() {
}
class ConversationResponse::_Internal {
 public:
};

ConversationResponse::ConversationResponse()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Seq2SeqGRPC.ConversationResponse)
}
ConversationResponse::ConversationResponse(const ConversationResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  trans_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_trans_id().empty()) {
    trans_id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.trans_id_);
  }
  text_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_text().empty()) {
    text_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
  state_ = from.state_;
  // @@protoc_insertion_point(copy_constructor:Seq2SeqGRPC.ConversationResponse)
}

void ConversationResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ConversationResponse_seq2seq_5fservice_2eproto.base);
  trans_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  text_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  state_ = 0;
}

ConversationResponse::~ConversationResponse() {
  // @@protoc_insertion_point(destructor:Seq2SeqGRPC.ConversationResponse)
  SharedDtor();
}

void ConversationResponse::SharedDtor() {
  trans_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  text_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ConversationResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ConversationResponse& ConversationResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ConversationResponse_seq2seq_5fservice_2eproto.base);
  return *internal_default_instance();
}


void ConversationResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Seq2SeqGRPC.ConversationResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  trans_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  text_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  state_ = 0;
  _internal_metadata_.Clear();
}

const char* ConversationResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string trans_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_trans_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Seq2SeqGRPC.ConversationResponse.trans_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .Seq2SeqGRPC.ConversationResponse.State state = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_state(static_cast<::Seq2SeqGRPC::ConversationResponse_State>(val));
        } else goto handle_unusual;
        continue;
      // string text = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_text();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Seq2SeqGRPC.ConversationResponse.text"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ConversationResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Seq2SeqGRPC.ConversationResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string trans_id = 1;
  if (this->trans_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_trans_id().data(), static_cast<int>(this->_internal_trans_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Seq2SeqGRPC.ConversationResponse.trans_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_trans_id(), target);
  }

  // .Seq2SeqGRPC.ConversationResponse.State state = 2;
  if (this->state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_state(), target);
  }

  // string text = 3;
  if (this->text().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_text().data(), static_cast<int>(this->_internal_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Seq2SeqGRPC.ConversationResponse.text");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_text(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Seq2SeqGRPC.ConversationResponse)
  return target;
}

size_t ConversationResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Seq2SeqGRPC.ConversationResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string trans_id = 1;
  if (this->trans_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_trans_id());
  }

  // string text = 3;
  if (this->text().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_text());
  }

  // .Seq2SeqGRPC.ConversationResponse.State state = 2;
  if (this->state() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_state());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConversationResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Seq2SeqGRPC.ConversationResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ConversationResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ConversationResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Seq2SeqGRPC.ConversationResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Seq2SeqGRPC.ConversationResponse)
    MergeFrom(*source);
  }
}

void ConversationResponse::MergeFrom(const ConversationResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Seq2SeqGRPC.ConversationResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.trans_id().size() > 0) {

    trans_id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.trans_id_);
  }
  if (from.text().size() > 0) {

    text_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
  if (from.state() != 0) {
    _internal_set_state(from._internal_state());
  }
}

void ConversationResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Seq2SeqGRPC.ConversationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConversationResponse::CopyFrom(const ConversationResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Seq2SeqGRPC.ConversationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConversationResponse::IsInitialized() const {
  return true;
}

void ConversationResponse::InternalSwap(ConversationResponse* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  trans_id_.Swap(&other->trans_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  text_.Swap(&other->text_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(state_, other->state_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ConversationResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Seq2SeqGRPC
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Seq2SeqGRPC::ConversationInput* Arena::CreateMaybeMessage< ::Seq2SeqGRPC::ConversationInput >(Arena* arena) {
  return Arena::CreateInternal< ::Seq2SeqGRPC::ConversationInput >(arena);
}
template<> PROTOBUF_NOINLINE ::Seq2SeqGRPC::ConversationResponse* Arena::CreateMaybeMessage< ::Seq2SeqGRPC::ConversationResponse >(Arena* arena) {
  return Arena::CreateInternal< ::Seq2SeqGRPC::ConversationResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
