// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: seq2seq_service.proto
#ifndef GRPC_seq2seq_5fservice_2eproto__INCLUDED
#define GRPC_seq2seq_5fservice_2eproto__INCLUDED

#include "seq2seq_service.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace Seq2SeqGRPC {

class Seq2SeqService final {
 public:
  static constexpr char const* service_full_name() {
    return "Seq2SeqGRPC.Seq2SeqService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::Seq2SeqGRPC::ConversationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Seq2SeqGRPC::ConversationResponse>> AsyncRespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Seq2SeqGRPC::ConversationResponse>>(AsyncRespondToTextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Seq2SeqGRPC::ConversationResponse>> PrepareAsyncRespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Seq2SeqGRPC::ConversationResponse>>(PrepareAsyncRespondToTextRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void RespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput* request, ::Seq2SeqGRPC::ConversationResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RespondToText(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Seq2SeqGRPC::ConversationResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput* request, ::Seq2SeqGRPC::ConversationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput* request, ::Seq2SeqGRPC::ConversationResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RespondToText(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Seq2SeqGRPC::ConversationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RespondToText(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Seq2SeqGRPC::ConversationResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Seq2SeqGRPC::ConversationResponse>* AsyncRespondToTextRaw(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Seq2SeqGRPC::ConversationResponse>* PrepareAsyncRespondToTextRaw(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::Seq2SeqGRPC::ConversationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Seq2SeqGRPC::ConversationResponse>> AsyncRespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Seq2SeqGRPC::ConversationResponse>>(AsyncRespondToTextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Seq2SeqGRPC::ConversationResponse>> PrepareAsyncRespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Seq2SeqGRPC::ConversationResponse>>(PrepareAsyncRespondToTextRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void RespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput* request, ::Seq2SeqGRPC::ConversationResponse* response, std::function<void(::grpc::Status)>) override;
      void RespondToText(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Seq2SeqGRPC::ConversationResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput* request, ::Seq2SeqGRPC::ConversationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RespondToText(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput* request, ::Seq2SeqGRPC::ConversationResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RespondToText(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Seq2SeqGRPC::ConversationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RespondToText(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Seq2SeqGRPC::ConversationResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Seq2SeqGRPC::ConversationResponse>* AsyncRespondToTextRaw(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Seq2SeqGRPC::ConversationResponse>* PrepareAsyncRespondToTextRaw(::grpc::ClientContext* context, const ::Seq2SeqGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RespondToText_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RespondToText(::grpc::ServerContext* context, const ::Seq2SeqGRPC::ConversationInput* request, ::Seq2SeqGRPC::ConversationResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RespondToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RespondToText() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RespondToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RespondToText(::grpc::ServerContext* /*context*/, const ::Seq2SeqGRPC::ConversationInput* /*request*/, ::Seq2SeqGRPC::ConversationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRespondToText(::grpc::ServerContext* context, ::Seq2SeqGRPC::ConversationInput* request, ::grpc::ServerAsyncResponseWriter< ::Seq2SeqGRPC::ConversationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RespondToText<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RespondToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RespondToText() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::Seq2SeqGRPC::ConversationInput, ::Seq2SeqGRPC::ConversationResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::Seq2SeqGRPC::ConversationInput* request, ::Seq2SeqGRPC::ConversationResponse* response) { return this->RespondToText(context, request, response); }));}
    void SetMessageAllocatorFor_RespondToText(
        ::grpc::experimental::MessageAllocator< ::Seq2SeqGRPC::ConversationInput, ::Seq2SeqGRPC::ConversationResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::Seq2SeqGRPC::ConversationInput, ::Seq2SeqGRPC::ConversationResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RespondToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RespondToText(::grpc::ServerContext* /*context*/, const ::Seq2SeqGRPC::ConversationInput* /*request*/, ::Seq2SeqGRPC::ConversationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RespondToText(
      ::grpc::CallbackServerContext* /*context*/, const ::Seq2SeqGRPC::ConversationInput* /*request*/, ::Seq2SeqGRPC::ConversationResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RespondToText(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::Seq2SeqGRPC::ConversationInput* /*request*/, ::Seq2SeqGRPC::ConversationResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_RespondToText<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_RespondToText<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RespondToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RespondToText() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RespondToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RespondToText(::grpc::ServerContext* /*context*/, const ::Seq2SeqGRPC::ConversationInput* /*request*/, ::Seq2SeqGRPC::ConversationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RespondToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RespondToText() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RespondToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RespondToText(::grpc::ServerContext* /*context*/, const ::Seq2SeqGRPC::ConversationInput* /*request*/, ::Seq2SeqGRPC::ConversationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRespondToText(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RespondToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RespondToText() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RespondToText(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_RespondToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RespondToText(::grpc::ServerContext* /*context*/, const ::Seq2SeqGRPC::ConversationInput* /*request*/, ::Seq2SeqGRPC::ConversationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RespondToText(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RespondToText(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RespondToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RespondToText() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Seq2SeqGRPC::ConversationInput, ::Seq2SeqGRPC::ConversationResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::Seq2SeqGRPC::ConversationInput, ::Seq2SeqGRPC::ConversationResponse>* streamer) {
                       return this->StreamedRespondToText(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RespondToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RespondToText(::grpc::ServerContext* /*context*/, const ::Seq2SeqGRPC::ConversationInput* /*request*/, ::Seq2SeqGRPC::ConversationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRespondToText(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Seq2SeqGRPC::ConversationInput,::Seq2SeqGRPC::ConversationResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RespondToText<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RespondToText<Service > StreamedService;
};

}  // namespace Seq2SeqGRPC


#endif  // GRPC_seq2seq_5fservice_2eproto__INCLUDED
